
way_num: 5
shot_num: 5
query_num: 15
eval_query: 15
eval_way: 5
eval_shot: 5
gamma: 0.5
epoch: 200
lr: 0.0002

data_root: ./data/miniImagenet
#pretrain_path: saves/initialization/miniimagenet/Res12-pre.pth


classifier:
  name: INSTA
  kwargs:
    gamma: 0.5
    temperature: 1
    

backbone:
  name: resnet12
  kwargs:
      maxpool_last2: False
      is_flatten: False

optimizer:
  kwargs:
    lr: 0.0002
    momentum: 0.9
    nesterov: true
    weight_decay: 0.0005
  name: SGD
  other: null


lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 200
    eta_min: 0.00001
    
    
